# Generated by Django 2.1.2 on 2018-10-14 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'material',
            },
        ),
        migrations.CreateModel(
            name='Rock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'rock',
            },
        ),
        migrations.CreateModel(
            name='RockComposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.PROTECT, to='rocks.Material')),
                ('rock', models.ForeignKey(db_column='rock_id', on_delete=django.db.models.deletion.CASCADE, to='rocks.Rock')),
            ],
            options={
                'db_table': 'rock_composition',
            },
        ),
        migrations.AddField(
            model_name='rock',
            name='materials',
            field=models.ManyToManyField(through='rocks.RockComposition', to='rocks.Material'),
        ),
    ]
