# Generated by Django 2.1.2 on 2018-12-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rock',
            name='added_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rock',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rock',
            name='picture',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
