# Generated by Django 2.1.2 on 2018-10-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('unit_of_measure', models.CharField(max_length=20)),
                ('picture', models.ImageField(null=True, upload_to='media/')),
                ('type', models.CharField(choices=[('Physical', 'PHYSICAL'), ('Virtual', 'VIRTUAL')], max_length=15, null=True)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sensor',
            },
        ),
    ]
