# Generated by Django 2.1.2 on 2018-10-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('unit_of_measure', models.CharField(max_length=20)),
                ('picture', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
