# Generated by Django 2.1.2 on 2018-10-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='abbreviation',
            field=models.CharField(max_length=30),
        ),
    ]
