# Generated by Django 2.1.2 on 2019-01-08 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
    ]
