# Generated by Django 2.1.2 on 2018-10-07 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sensor',
            table='sensor',
        ),
    ]
