# Generated by Django 2.1.2 on 2018-10-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_auto_20181007_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='type',
            field=models.CharField(choices=[('REAL', 'Real'), ('DERIVED', 'Derived')], max_length=15, null=True),
        ),
    ]
