# Generated by Django 2.1.2 on 2018-10-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_sensor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='type',
            field=models.CharField(choices=[('REAL', 'Real'), ('VIRTUAL', 'Virtual')], max_length=15, null=True),
        ),
    ]
