# Generated by Django 2.1.2 on 2018-10-07 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_auto_20181007_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='added_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensor',
            name='type',
            field=models.CharField(choices=[('PHYSICAL', 'Physical'), ('VIRTUAL', 'Virtual')], max_length=15, null=True),
        ),
    ]
