# Generated by Django 2.1.2 on 2018-10-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_auto_20181007_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='abbreviation',
            field=models.CharField(default=7, max_length=10),
            preserve_default=False,
        ),
    ]
