# Generated by Django 2.1.2 on 2018-10-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_sensor_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='type',
            field=models.CharField(choices=[('Physical', 'PHYSICAL'), ('Virtual', 'VIRTUAL')], max_length=15, null=True),
        ),
    ]
