# Generated by Django 2.1.2 on 2018-10-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_auto_20181007_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='picture',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
