# Generated by Django 2.1.2 on 2019-01-03 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_occupation_specialization_specificoccupation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specificoccupation',
            old_name='occupation_id',
            new_name='occupation',
        ),
        migrations.RenameField(
            model_name='specificoccupation',
            old_name='specialization_id',
            new_name='specialization',
        ),
    ]
