# Generated by Django 2.1.2 on 2019-01-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190103_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='name',
            field=models.CharField(default='defaul', max_length=50),
            preserve_default=False,
        ),
    ]
