# Generated by Django 2.1.2 on 2019-01-08 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_specialization_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specificoccupation',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='specificoccupation',
            name='specialization',
        ),
        migrations.DeleteModel(
            name='SpecificOccupation',
        ),
    ]
