# Generated by Django 2.1.2 on 2019-01-08 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190108_2310'),
    ]

    operations = [
    ]
